### ISSUE TITLE
"budget_unit" field not updatable in PUT and POST methods for tasks

### ISSUE THREAD

**Issue by thierrylafaye** [timecamp2/timecamp-api#3]
Hi all,

After testing extensively (I thought I was doing something incorrect myself for being still a beginner in programming), but the documentation of your API clearly states only the fields available for POST and PUT. Would there be a plan to add for more fields, particularly "budget_unit" which is the one I am interested in?

Cheers,
Thierry

**Comment by timecamp2** [comment]
Yes, we will add those maybe even today.

**Comment by timecamp2** [comment]
Should be working now.
